# Generated by Django 4.2.7 on 2023-11-24 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='post/%m', verbose_name='img')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Img', to='blog.post')),
            ],
        ),
    ]
