# Generated by Django 4.2.3 on 2023-11-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_image_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to='post/%m'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
